export type LeadershipLevel = "senior" | "pastoral" | "ministry";
export type LeadershipRole = "general-overseer" | "general-overseers-wife" | "pastor" | "assistant-pastor" | "associate-pastor" | "bishop" | "apostle" | "ordained-minister" | "ministry-leader";
export type LeadershipCategory = { id: string; name: string; slug: string; rank: number; published: boolean };
export type LeaderSocialLinks = { website?: string; facebook?: string; instagram?: string; youtube?: string; linkedin?: string };
export type Leader = { id: string; slug: string; name: string; role: string; level: LeadershipLevel; categoryId?: string; ministry?: string; photoUrl: string; photoPublicId?: string; photoAlt: string; shortBio: string; biography: string; socialLinks?: LeaderSocialLinks; order: number; published: boolean };
export type AboutContent = { intro: string; mission: string; vision: string; legacyTitle: string; legacyText: string; storyTitle: string; storyText: string };
export const leadershipRoles: { value: LeadershipRole; label: string; level: LeadershipLevel }[] = [{ value: "general-overseer", label: "General Overseer", level: "senior" }, { value: "general-overseers-wife", label: "General Overseer's Wife", level: "senior" }, { value: "pastor", label: "Pastor", level: "pastoral" }, { value: "assistant-pastor", label: "Assistant Pastor", level: "pastoral" }, { value: "associate-pastor", label: "Associate Pastor", level: "pastoral" }, { value: "bishop", label: "Bishop", level: "pastoral" }, { value: "apostle", label: "Apostle", level: "ministry" }, { value: "ordained-minister", label: "Ordained Minister", level: "ministry" }, { value: "ministry-leader", label: "Ministry Leader", level: "ministry" }];
export const defaultAboutContent: AboutContent = { intro: "The Life Global Outreach Ministries (TLGOM) is a Christian ministry committed to leading people to Christ massively, worldwide, and establishing them in the Word of God.", mission: "To lead people to Christ massively, worldwide, and establish them in the Word of God through worship, prayer, teaching, discipleship, and outreach.", vision: "To see transformed lives and communities reached by the gospel, growing together as a family of faith and serving God’s purpose in the world.", legacyTitle: "A heritage of faith and service.", legacyText: "The ministry honours the people God has used throughout its journey and the faithful service that has helped shape its witness. The legacy of our late First Lady remains part of the story we carry with gratitude, dignity, and hope in Christ.", storyTitle: "Our Story", storyText: "Discover the journey of The Life Global Outreach Ministries—how the ministry began, the people God used, the milestones along the way, and the vision that continues to drive the ministry today." };
export const emptyLeader = (id = ""): Leader => ({ id, slug: "", name: "", role: "pastor", level: "pastoral", categoryId: "", ministry: "", photoUrl: "", photoPublicId: "", photoAlt: "", shortBio: "", biography: "", socialLinks: {}, order: 0, published: true });
export function roleInfo(role: string) { return leadershipRoles.find((item) => item.value === role) || { value: role as LeadershipRole, label: role || "Leader", level: "ministry" as LeadershipLevel }; }
export function leaderSlug(name: string) { return name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
