import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { getPublicCollection, getPublicDocument } from "@/lib/firebase/public-data";
import { defaultAboutContent, roleInfo, type AboutContent, type Leader, type LeadershipCategory } from "@/lib/about";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "About The Life Global Outreach Ministries | TLGOM", description: "Learn about The Life Global Outreach Ministries (TLGOM), our mission, vision, leadership, legacy and journey of reaching people for Christ and establishing them in the Word of God.", alternates: { canonical: "/about" }, openGraph: { title: "About The Life Global Outreach Ministries | TLGOM", description: "Learn about TLGOM, its mission, vision, leadership, legacy and journey of faith.", url: "/about", type: "website", images: [{ url: "/logo.png", width: 512, height: 512, alt: "The Life Global Outreach Ministries logo" }] }, twitter: { card: "summary_large_image", title: "About TLGOM", description: "Learn about TLGOM, its mission, vision, leadership, legacy and journey of faith.", images: ["/logo.png"] } };
function LeaderCard({ leader, featured = false }: { leader: Leader; featured?: boolean }) { const role = roleInfo(leader.role); return <article className={featured ? "about-leader-card featured" : "about-leader-card"}>{leader.photoUrl ? <img src={leader.photoUrl} alt={leader.photoAlt || `${leader.name}, ${role.label} at The Life Global Outreach Ministries`} /> : <div className="about-leader-placeholder" aria-hidden="true">TLGOM</div>}<div><p className="about-leader-role">{role.label}</p><h3>{leader.name}</h3>{leader.shortBio && <p>{leader.shortBio}</p>}</div></article>; }
function leaderKey(leader: Leader, index: number) { return `${leader.id || leader.slug || leader.name || "leader"}-${index}`; }
function sortLeaders(leaders: Leader[]) { return leaders.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name)); }
function LeadershipGroup({ title, leaders, featured = false }: { title: string; leaders: Leader[]; featured?: boolean }) { if (!leaders.length) return null; return <div className="about-hierarchy"><h3>{title}</h3><div className={featured ? "about-senior-grid" : "about-leader-grid"}>{leaders.map((leader, index) => <LeaderCard leader={leader} featured={featured} key={leaderKey(leader, index)} />)}</div></div>; }

export default async function AboutPage() { const aboutDoc = await getPublicDocument("siteSettings", "about"); const content = { ...defaultAboutContent, ...(aboutDoc || {}) } as AboutContent; const leaders = (await getPublicCollection("leadership") as Leader[]).filter((leader) => leader.published); const categories = (await getPublicCollection("leadershipCategories") as LeadershipCategory[]).filter((category) => category.published).sort((a, b) => a.rank - b.rank || a.name.localeCompare(b.name)); const categorizedIds = new Set<string>(); const categoryGroups = categories.map((category) => { const group = sortLeaders(leaders.filter((leader) => leader.categoryId === category.id)); group.forEach((leader) => categorizedIds.add(leader.id)); return { category, group }; }).filter((item) => item.group.length); const uncategorized = leaders.filter((leader) => !categorizedIds.has(leader.id)); const senior = sortLeaders(uncategorized.filter((leader) => leader.level === "senior")); const pastoral = sortLeaders(uncategorized.filter((leader) => leader.level === "pastoral")); const ministry = sortLeaders(uncategorized.filter((leader) => leader.level === "ministry")); const jsonLd = { "@context": "https://schema.org", "@type": "ReligiousOrganization", name: "The Life Global Outreach Ministries", alternateName: "TLGOM", url: "https://tlgom.vercel.app/about", description: content.intro, member: leaders.map((leader) => ({ "@type": "Person", name: leader.name, jobTitle: roleInfo(leader.role).label })) };
  return <main className="about-page"><SiteHeader /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="about-hero"><div className="container"><p className="section-kicker">The Life Global Outreach Ministries</p><h1>About TLGOM</h1><p>{content.intro}</p></div></section><section className="about-content"><div className="container about-intro-copy"><p className="section-kicker">About the ministry</p><h2>A people formed by the Word and sent with the gospel.</h2><p>{content.intro} The ministry’s identity carries the heritage of The Life and Fire Assembly—The Life representing the Word of God and The Fire representing deliverance and the power of God.</p></div><div className="container about-mission-grid"><article><h2>Our mission</h2><p>{content.mission}</p></article><article><h2>Our vision</h2><p>{content.vision}</p></article></div><section className="container about-leadership"><div className="about-section-heading"><p className="section-kicker">People who serve</p><h2>Our leadership</h2><p>Meet the people entrusted with serving and guiding the work of The Life Global Outreach Ministries.</p></div>{categoryGroups.map(({ category, group }) => <LeadershipGroup key={category.id} title={category.name} leaders={group} featured={category.rank === 1} />)}{categoryGroups.length === 0 && <><LeadershipGroup title="Senior leadership" leaders={senior} featured /><LeadershipGroup title="Pastoral leadership" leaders={pastoral} /><LeadershipGroup title="Ministry leadership" leaders={ministry} /></>}{categoryGroups.length > 0 && <><LeadershipGroup title="Senior leadership" leaders={senior} featured /><LeadershipGroup title="Pastoral leadership" leaders={pastoral} /><LeadershipGroup title="Ministry leadership" leaders={ministry} /></>}{leaders.length === 0 && <p className="about-empty-leadership">Leadership profiles will be added here as the ministry publishes them.</p>}</section><section className="about-legacy"><div className="container about-legacy-inner"><div><p className="section-kicker">Legacy</p><h2>{content.legacyTitle}</h2></div><p>{content.legacyText}</p></div></section><section className="container about-story"><p className="section-kicker">The journey continues</p><h2>{content.storyTitle}</h2><p>{content.storyText}</p><div className="about-final-cta"><Link href="/about/history">Discover Our Story <span aria-hidden="true">→</span></Link></div></section></section><SiteFooter /></main>;
}
