import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { getPublicCollection, getPublicDocument } from "@/lib/firebase/public-data";
import { defaultAboutContent, roleInfo, type AboutContent, type Leader } from "@/lib/about";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "About The Life Global Outreach Ministries | TLGOM", description: "Learn about The Life Global Outreach Ministries (TLGOM), our mission, vision, leadership, legacy and journey of reaching people for Christ and establishing them in the Word of God.", alternates: { canonical: "/about" }, openGraph: { title: "About The Life Global Outreach Ministries | TLGOM", description: "Learn about TLGOM, its mission, vision, leadership, legacy and journey of faith.", url: "/about", type: "website", images: [{ url: "/logo.png", width: 512, height: 512, alt: "The Life Global Outreach Ministries logo" }] }, twitter: { card: "summary_large_image", title: "About TLGOM", description: "Learn about TLGOM, its mission, vision, leadership, legacy and journey of faith.", images: ["/logo.png"] } };

function LeaderCard({ leader, featured = false }: { leader: Leader; featured?: boolean }) { const role = roleInfo(leader.role); return <article className={featured ? "about-leader-card featured" : "about-leader-card"}>{leader.photoUrl ? <img src={leader.photoUrl} alt={leader.photoAlt || `${leader.name}, ${role.label} at The Life Global Outreach Ministries`} /> : <div className="about-leader-placeholder" aria-hidden="true">TLGOM</div>}<div><p className="about-leader-role">{role.label}</p><h3>{leader.name}</h3>{leader.shortBio && <p>{leader.shortBio}</p>}</div></article>; }
function groupLeaders(leaders: Leader[], level: Leader["level"]) { return leaders.filter((leader) => leader.level === level && leader.published).sort((a, b) => a.order - b.order || a.name.localeCompare(b.name)); }
function leaderKey(leader: Leader, index: number) { return `${leader.id || leader.slug || leader.name || "leader"}-${index}`; }

export default async function AboutPage() { const aboutDoc = await getPublicDocument("siteSettings", "about"); const content = { ...defaultAboutContent, ...(aboutDoc || {}) } as AboutContent; const leaders = (await getPublicCollection("leadership") as Leader[]).filter((leader) => leader.published); const senior = leaders.filter((leader) => leader.level === "senior").sort((a, b) => a.order - b.order); const pastoral = groupLeaders(leaders, "pastoral"); const ministry = groupLeaders(leaders, "ministry"); const jsonLd = { "@context": "https://schema.org", "@type": "ReligiousOrganization", name: "The Life Global Outreach Ministries", alternateName: "TLGOM", url: "https://tlgom.vercel.app/about", description: content.intro, member: leaders.map((leader) => ({ "@type": "Person", name: leader.name, jobTitle: roleInfo(leader.role).label })) };
  return <main className="about-page"><SiteHeader /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="about-hero"><div className="container"><p className="section-kicker">The Life Global Outreach Ministries</p><h1>About TLGOM</h1><p>{content.intro}</p></div></section><section className="about-content"><div className="container about-intro-copy"><p className="section-kicker">About the ministry</p><h2>A people formed by the Word and sent with the gospel.</h2><p>{content.intro} The ministry’s identity carries the heritage of The Life and Fire Assembly—The Life representing the Word of God and The Fire representing deliverance and the power of God.</p></div><div className="container about-mission-grid"><article><h2>Our mission</h2><p>{content.mission}</p></article><article><h2>Our vision</h2><p>{content.vision}</p></article></div><section className="container about-leadership"><div className="about-section-heading"><p className="section-kicker">People who serve</p><h2>Our leadership</h2><p>Meet the people entrusted with serving and guiding the work of The Life Global Outreach Ministries.</p></div>{senior.length > 0 && <div className="about-hierarchy"><h3>Senior leadership</h3><div className="about-senior-grid">{senior.map((leader, index) => <LeaderCard leader={leader} featured key={leaderKey(leader, index)} />)}</div></div>}{pastoral.length > 0 && <div className="about-hierarchy"><h3>Pastoral leadership</h3><div className="about-leader-grid">{pastoral.map((leader, index) => <LeaderCard leader={leader} key={leaderKey(leader, index)} />)}</div></div>}{ministry.length > 0 && <div className="about-hierarchy"><h3>Ministry leadership</h3><div className="about-leader-grid">{ministry.map((leader, index) => <LeaderCard leader={leader} key={leaderKey(leader, index)} />)}</div></div>}{leaders.length === 0 && <p className="about-empty-leadership">Leadership profiles will be added here as the ministry publishes them.</p>}</section><section className="about-legacy"><div className="container about-legacy-inner"><div><p className="section-kicker">Legacy</p><h2>{content.legacyTitle}</h2></div><p>{content.legacyText}</p></div></section><section className="container about-story"><p className="section-kicker">The journey continues</p><h2>{content.storyTitle}</h2><p>{content.storyText}</p><div className="about-final-cta"><Link href="/about/history">Discover Our Story <span aria-hidden="true">→</span></Link></div></section></section><SiteFooter /></main>;
}
