"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { collection, deleteDoc, doc, onSnapshot, serverTimestamp, setDoc, updateDoc } from "firebase/firestore";
import { onAuthStateChanged, type User } from "firebase/auth";
import { ArrowLeft, Eye, EyeOff, LoaderCircle, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { auth, db, firebaseReady } from "@/lib/firebase/client";

type Submission = { id: string; type?: string; name?: string; message?: string; viewed?: boolean; createdAt?: unknown };
type PublicTestimony = { id: string; submissionId?: string; name?: string; message?: string; showName?: boolean; published?: boolean; order?: number };
function abbreviation(name: string) { return name.trim().split(/\s+/).filter(Boolean).map((part) => `${part.charAt(0).toUpperCase()}.`).join(" "); }

export default function TestimoniesAdminPage() { const router = useRouter(); const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); const [submissions, setSubmissions] = useState<Submission[]>([]); const [published, setPublished] = useState<PublicTestimony[]>([]); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, (next) => { setUser(next); setReady(true); }); }, []); useEffect(() => { if (ready && !user) router.replace("/control-room?next=/control-room/testimonies"); }, [ready, user, router]); useEffect(() => { if (!db || !user) return; const stopSubmissions = onSnapshot(collection(db, "submissions"), (snap) => { setSubmissions(snap.docs.map((item) => ({ ...item.data(), id: item.id } as Submission)).filter((item) => item.type === "testimony").sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || "")))); }); const stopPublished = onSnapshot(collection(db, "testimonies"), (snap) => { setPublished(snap.docs.map((item) => ({ ...item.data(), id: item.id } as PublicTestimony))); }); return () => { stopSubmissions(); stopPublished(); }; }, [user]);
  async function selectSubmission(item: Submission) { if (!db || !item.message) return; const existing = published.find((entry) => entry.submissionId === item.id); setBusy(item.id); setError(""); try { if (existing) await deleteDoc(doc(db, "testimonies", existing.id)); else await setDoc(doc(db, "testimonies", item.id), { submissionId: item.id, name: item.name || "", message: item.message, showName: false, published: true, order: published.length, updatedAt: serverTimestamp() }); setMessage(existing ? "Testimony removed from the public page." : "Testimony selected for the public page."); } catch { setError("Could not update this testimony."); } finally { setBusy(""); } }
  async function toggleName(item: Submission) { if (!db) return; const existing = published.find((entry) => entry.submissionId === item.id); if (!existing) return; setBusy(item.id); try { await updateDoc(doc(db, "testimonies", existing.id), { showName: !existing.showName, updatedAt: serverTimestamp() }); } catch { setError("Could not update the name display setting."); } finally { setBusy(""); } }
  if (!firebaseReady || !ready || !user) return <main className="login-page"><LoaderCircle className="spin" size={28} /></main>;
  return <main className="admin-page"><section className="admin-content"><Link className="admin-back" href="/control-room"><ArrowLeft size={16} /> Back to Control Room</Link><div className="admin-topbar"><div><p className="admin-kicker">Public stories</p><h1>Choose testimonies</h1><p className="admin-intro">Select visitor testimonies to display publicly. Names are hidden by default; when enabled, only initials are shown.</p></div></div>{message && <div className="admin-notice success">{message}</div>}{error && <div className="admin-notice error">{error}</div>}<div className="slides-header"><div><p className="admin-kicker">Submitted testimonies</p><h2>{submissions.length} {submissions.length === 1 ? "submission" : "submissions"}</h2></div></div><div className="submission-list">{submissions.length === 0 ? <div className="empty-slides"><h3>No testimony submissions yet</h3><p>Submitted testimonies will appear here.</p></div> : submissions.map((item) => { const selected = published.find((entry) => entry.submissionId === item.id); return <article className={`submission-row ${selected ? "viewed" : "unread"}`} key={item.id}><div className="submission-row-heading"><span className="submission-type">{selected ? "Shown publicly" : "Not published"}</span><span className="new-label">{item.name || "Anonymous"}</span></div><p className="submission-message">{item.message}</p><div className="testimony-admin-actions"><button className="submission-view-button" type="button" disabled={busy === item.id} onClick={() => selectSubmission(item)}>{busy === item.id ? <LoaderCircle className="spin" size={15} /> : selected ? <EyeOff size={15} /> : <Eye size={15} />} {selected ? "Remove from public" : "Show publicly"}</button>{selected && <button className="submission-view-button" type="button" disabled={busy === item.id} onClick={() => toggleName(item)}><Save size={15} /> {selected.showName ? `Showing ${abbreviation(item.name || "Anonymous")}` : "Show abbreviated name"}</button>}</div></article>; })}</div></section></main>; }
