"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import Link from "next/link";
import { onAuthStateChanged, type User } from "firebase/auth";
import { addDoc, collection, deleteDoc, doc, onSnapshot, updateDoc } from "firebase/firestore";
import { ArrowLeft, ArrowRight, Eye, EyeOff, FolderPlus, Images, LoaderCircle, Save, Trash2, UploadCloud } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { auth, db, firebaseReady } from "@/lib/firebase/client";
import type { GalleryAlbum, GalleryPhoto } from "@/lib/gallery";

async function uploadGalleryFile(file: File, token: string) {
  const response = await fetch("/api/cloudinary/sign", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ folder: "tlgom/gallery" }) });
  const signature = await response.json(); if (!response.ok) throw new Error(signature.error || "Could not authorize upload.");
  const form = new FormData(); form.append("file", file); form.append("api_key", signature.apiKey); form.append("timestamp", signature.timestamp); form.append("folder", signature.folder); form.append("signature", signature.signature);
  const upload = await fetch(`https://api.cloudinary.com/v1_1/${signature.cloudName}/image/upload`, { method: "POST", body: form }); const result = await upload.json();
  if (!upload.ok) throw new Error(result.error?.message || "Cloudinary upload failed."); return { url: result.secure_url as string, publicId: result.public_id as string };
}

export default function GalleryAlbumAdminPage() {
  const params = useParams<{ id: string }>(); const albumId = params.id; const router = useRouter();
  const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); const [albums, setAlbums] = useState<GalleryAlbum[]>([]); const [photos, setPhotos] = useState<GalleryPhoto[]>([]);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const album = albums.find((item) => item.id === albumId); const children = albums.filter((item) => item.parentId === albumId); const albumPhotos = photos.filter((photo) => photo.albumId === albumId).sort((a, b) => (a.order || 0) - (b.order || 0));

  useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, (next) => { setUser(next); setReady(true); }); }, []);
  useEffect(() => { if (ready && !user) router.replace(`/control-room?next=${encodeURIComponent(`/control-room/gallery/${albumId}`)}`); }, [ready, user, router, albumId]);
  useEffect(() => { if (!db || !user) return; const stopAlbums = onSnapshot(collection(db, "galleryAlbums"), (s) => setAlbums(s.docs.map((item) => ({ id: item.id, ...item.data() } as GalleryAlbum)))); const stopPhotos = onSnapshot(collection(db, "galleryPhotos"), (s) => setPhotos(s.docs.map((item) => ({ id: item.id, ...item.data() } as GalleryPhoto)))); return () => { stopAlbums(); stopPhotos(); }; }, [user]);

  const descendantIds = useMemo(() => { const ids = new Set<string>(); const visit = (id: string) => { albums.filter((item) => item.parentId === id).forEach((child) => { ids.add(child.id); visit(child.id); }); }; visit(albumId); return ids; }, [albums, albumId]);

  async function saveAlbum(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!db || !album) return; const form = new FormData(event.currentTarget); if (String(form.get("parentId") || "") === album.id || descendantIds.has(String(form.get("parentId") || ""))) { setError("An album cannot be moved inside itself or one of its children."); return; } setBusy(true); setError(""); try { await updateDoc(doc(db, "galleryAlbums", album.id), { name: String(form.get("name") || "").trim(), slug: String(form.get("slug") || "").trim().toLowerCase().replace(/[^a-z0-9-]+/g, "-"), description: String(form.get("description") || "").trim(), parentId: String(form.get("parentId") || ""), ministrySlug: String(form.get("ministrySlug") || "").trim() }); setMessage("Album details saved."); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Could not save album."); } finally { setBusy(false); } }

  async function createChild(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!db || !album) return; const formElement = event.currentTarget; const form = new FormData(formElement); setBusy(true); setError(""); try { await addDoc(collection(db, "galleryAlbums"), { name: String(form.get("name") || "").trim(), slug: String(form.get("slug") || "").trim().toLowerCase().replace(/[^a-z0-9-]+/g, "-"), description: String(form.get("description") || "").trim(), parentId: album.id, ministrySlug: String(form.get("ministrySlug") || "").trim(), coverImageUrl: "", coverPublicId: "", visible: true, order: children.length }); formElement.reset(); setMessage("Child album created."); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Could not create child album."); } finally { setBusy(false); } }

  async function uploadPhotos(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!db || !user || !album) return; const formElement = event.currentTarget; const files = Array.from(new FormData(formElement).getAll("photos")).filter((file): file is File => file instanceof File && Boolean(file.size)); if (!files.length) return; setBusy(true); setError(""); try { const uploaded: { url: string; publicId: string }[] = []; for (const file of files) { const image = await uploadGalleryFile(file, await user.getIdToken()); uploaded.push(image); await addDoc(collection(db, "galleryPhotos"), { albumId: album.id, imageUrl: image.url, publicId: image.publicId, visible: true, order: albumPhotos.length + uploaded.length - 1 }); } const cover = uploaded[Math.floor(Math.random() * uploaded.length)]; await updateDoc(doc(db, "galleryAlbums", album.id), { coverImageUrl: cover.url, coverPublicId: cover.publicId }); formElement.reset(); setMessage(`${files.length} photo${files.length === 1 ? "" : "s"} uploaded. A random upload is now the cover.`); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : "Could not upload photos."); } finally { setBusy(false); } }

  async function removePhoto(photo: GalleryPhoto) { if (!db || !album || !window.confirm("Remove this photo from the album?")) return; const currentAlbumId = album.id; const wasCover = album.coverPublicId === photo.publicId; try { if (photo.publicId && user) await fetch("/api/cloudinary/delete", { method: "POST", headers: { Authorization: `Bearer ${await user.getIdToken()}`, "Content-Type": "application/json" }, body: JSON.stringify({ publicId: photo.publicId }) }); await deleteDoc(doc(db, "galleryPhotos", photo.id)); if (wasCover) await updateDoc(doc(db, "galleryAlbums", currentAlbumId), { coverImageUrl: "", coverPublicId: "" }); } catch { setError("Could not remove photo."); } }
  async function movePhoto(photo: GalleryPhoto, direction: -1 | 1) { if (!db) return; const index = albumPhotos.findIndex((item) => item.id === photo.id); const other = albumPhotos[index + direction]; if (!other) return; await updateDoc(doc(db, "galleryPhotos", photo.id), { order: other.order ?? index + direction }); await updateDoc(doc(db, "galleryPhotos", other.id), { order: photo.order ?? index }); }

  if (!firebaseReady || !ready || !user || !album) return <main className="login-page"><LoaderCircle className="spin" size={28} /></main>;
  return <main className="admin-page"><section className="admin-content gallery-admin-detail">
    <Link className="admin-back" href={album.parentId ? `/control-room/gallery/${album.parentId}` : "/control-room/gallery"}><ArrowLeft size={16} /> {album.parentId ? "Back to parent album" : "Back to album tree"}</Link>
    <div className="gallery-admin-hero"><div><p className="admin-kicker">Album workspace</p><h1>{album.name}</h1><p className="admin-intro">/{album.slug}{album.ministrySlug ? ` · Connected to ${album.ministrySlug}` : ""}</p></div><Link className="gallery-public-link" href={`/photo-gallery/${album.slug}`} target="_blank">View public album <ArrowRight size={15} /></Link></div>
    {message && <div className="admin-notice success">{message}</div>}{error && <div className="admin-notice error">{error}</div>}
    <div className="gallery-detail-grid"><form className="sermon-form" onSubmit={saveAlbum}><div className="upload-title"><Save size={18} /><div><h2>Edit album</h2><p>Update this album’s identity or move it within the tree.</p></div></div><div className="sermon-form-grid"><label>Album name<input name="name" required defaultValue={album.name} /></label><label>Slug<input name="slug" required defaultValue={album.slug} /></label><label>Parent album<select name="parentId" defaultValue={album.parentId || ""}><option value="">Top-level album</option>{albums.filter((item) => item.id !== album.id && !descendantIds.has(item.id)).map((item) => <option key={item.id} value={item.id}>{item.name}{item.parentId ? " · nested" : ""}</option>)}</select></label><label>Connect to ministry slug <span className="field-note">Optional</span><input name="ministrySlug" defaultValue={album.ministrySlug || ""} placeholder="youth-ministry" /></label><label className="wide-field">Description<textarea name="description" defaultValue={album.description || ""} /></label></div><button className="admin-button" disabled={busy}>{busy ? "Saving..." : "Save album"}</button></form>
      <form className="sermon-form" onSubmit={createChild}><div className="upload-title"><FolderPlus size={18} /><div><h2>Add child album</h2><p>This new album will appear inside {album.name}.</p></div></div><div className="sermon-form-grid"><label>Album name<input name="name" required placeholder="2026 Outreach" /></label><label>Slug<input name="slug" required placeholder="2026-outreach" /></label><label>Connect to ministry slug <span className="field-note">Optional</span><input name="ministrySlug" placeholder="youth-ministry" /></label><label className="wide-field">Description<textarea name="description" placeholder="What visitors will find here." /></label></div><button className="admin-button" disabled={busy}>{busy ? "Creating..." : "Create child album"}</button></form></div>
    <form className="upload-card gallery-upload-card" onSubmit={uploadPhotos}><div className="upload-title"><UploadCloud size={19} /><div><h2>Upload photos</h2><p>Choose multiple images. One is selected randomly as this album’s cover.</p></div></div><input name="photos" type="file" accept="image/*" multiple required /><button className="admin-button" disabled={busy}>{busy ? "Uploading..." : "Upload photos"}</button></form>
    <section className="gallery-detail-section"><div className="slides-header"><div><p className="admin-kicker">Photos in this album</p><h2>{albumPhotos.length} {albumPhotos.length === 1 ? "photo" : "photos"}</h2></div><p>Reorder images or remove individual photos.</p></div>{albumPhotos.length ? <div className="gallery-detail-photo-grid">{albumPhotos.map((photo, index) => <article className="gallery-detail-photo" key={photo.id}><img src={photo.imageUrl} alt={photo.alt || `${album.name} photo ${index + 1}`} /><div className="gallery-detail-photo-actions"><span>#{index + 1}{album.coverPublicId === photo.publicId ? " · Cover" : ""}</span><button type="button" title="Move up" disabled={!index} onClick={() => movePhoto(photo, -1)}><ArrowLeft size={14} /></button><button type="button" title="Move down" disabled={index === albumPhotos.length - 1} onClick={() => movePhoto(photo, 1)}><ArrowRight size={14} /></button><button type="button" title="Remove photo" onClick={() => removePhoto(photo)}><Trash2 size={14} /></button></div></article>)}</div> : <div className="gallery-empty"><Images size={28} /><p>No images yet under this album.</p></div>}</section>
    <section className="gallery-detail-section"><div className="slides-header"><div><p className="admin-kicker">Nested albums</p><h2>{children.length} {children.length === 1 ? "child album" : "child albums"}</h2></div><p>Every child has its own workspace, so nesting can continue indefinitely.</p></div>{children.length ? <div className="gallery-child-grid">{children.sort((a, b) => (a.order || 0) - (b.order || 0)).map((child) => <Link className="gallery-child-card" href={`/control-room/gallery/${child.id}`} key={child.id}><div className="gallery-admin-album-cover" style={{ backgroundImage: child.coverImageUrl ? `url("${child.coverImageUrl}")` : undefined }}>{!child.coverImageUrl && <Images size={17} />}</div><span><strong>{child.name}</strong><small>/{child.slug}</small></span><ArrowRight size={17} /></Link>)}</div> : <div className="gallery-empty"><FolderPlus size={26} /><p>No child albums yet. Add one above when you need another level.</p></div>}</section>
  </section></main>;
}
