import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { getPublicCollection } from "@/lib/firebase/public-data";
import type { ArticleBlock, BlogPost } from "@/lib/blog";

export const dynamic = "force-dynamic";
async function findPost(slug: string) { const posts = await getPublicCollection("blogPosts") as BlogPost[]; return posts.find((post) => post.slug === slug && post.status === "published"); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = await findPost(slug); const title = post?.seoTitle || post?.title || "Article"; const description = post?.metaDescription || post?.excerpt || "Christian articles from The Life Global Outreach Ministries."; return { title, description, alternates: { canonical: `/blog/${slug}` }, openGraph: { title: post?.ogTitle || title, description: post?.ogDescription || description, url: `/blog/${slug}`, type: "article", images: [{ url: post?.ogImage || post?.featuredImage || "/logo.png", width: 1200, height: 630, alt: post?.featuredImageAlt || title }] }, twitter: { card: "summary_large_image", title, description, images: [post?.ogImage || post?.featuredImage || "/logo.png"] } }; }
function Block({ block }: { block: ArticleBlock }) { if (block.type === "divider") return <hr />; if (block.type === "image" && block.imageUrl) return <figure><img src={block.imageUrl} alt={block.imageAlt || "Article image"} /></figure>; if (block.type === "gallery") return <div className="article-gallery">{(block.images || []).map((image, index) => <img key={`${image.url}-${index}`} src={image.url} alt={image.alt || "Article gallery image"} />)}</div>; if (block.type === "heading") return block.level === 3 ? <h3 dangerouslySetInnerHTML={{ __html: block.content || "" }} /> : <h2 dangerouslySetInnerHTML={{ __html: block.content || "" }} />; if (block.type === "quote") return <blockquote dangerouslySetInnerHTML={{ __html: block.content || "" }} />; if (block.type === "bullet-list") return <ul dangerouslySetInnerHTML={{ __html: block.content || "" }} />; if (block.type === "numbered-list") return <ol dangerouslySetInnerHTML={{ __html: block.content || "" }} />; if (block.type === "callout") return <aside className={`article-callout ${block.variant || "info"}`}><strong>{block.title || "Note"}</strong><div dangerouslySetInnerHTML={{ __html: block.content || "" }} /></aside>; if (block.type === "cta-button") return <p><a className="article-cta" href={block.url || "#"}>{block.label || "Learn more"}</a></p>; if (block.type === "link-embed") return <p><a className="article-link-embed" href={block.url || "#"}>{block.label || block.url}</a></p>; return <div className="article-rich-content" dangerouslySetInnerHTML={{ __html: block.content || "" }} />; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const post = await findPost(slug); if (!post) return <main className="blog-page"><SiteHeader /><div className="container blog-empty"><h1>Article not found</h1><Link href="/blog">Return to articles</Link></div><SiteFooter /></main>; return <main className="article-page"><SiteHeader /><article className="article"><div className="container article-header"><Link href="/blog">← Back to articles</Link><p className="section-kicker">{post.category || "TLGOM journal"} · {post.readTime || 4} min read</p><h1>{post.title}</h1><p className="article-excerpt">{post.excerpt}</p>{post.featuredImage && <img className="article-featured-image" src={post.featuredImage} alt={post.featuredImageAlt || post.title} />}</div><div className="container article-body">{(post.blocks || []).map((block, index) => <Block block={block} key={`${block.id || block.type}-${index}`} />)}</div></article><SiteFooter /></main>; }
