/* eslint-disable react/no-unescaped-entities */
"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";
import { ArrowRight, ChevronDown, Menu, X } from "lucide-react";
import { collection, doc, onSnapshot } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import type { SlideshowImage } from "@/lib/slideshow";
import type { Sermon } from "@/lib/sermons";
import { getYouTubeThumbnailUrl } from "@/lib/sermons";
import type { ChurchEvent } from "@/lib/events";
import { formatEventDate, getNextEventDate } from "@/lib/events";
import type { GalleryAlbum, GalleryPhoto } from "@/lib/gallery";
import SubmissionForms, { SubmissionContent } from "@/components/SubmissionForms";
import HomepageGallerySection from "@/components/HomepageGallerySection";
import SiteFooter from "@/components/SiteFooter";
import SermonCard from "@/components/SermonCard";
import EventCard from "@/components/EventCard";

const navItems = [["Home", "/"], ["About", "/about-us"], ["Events", "/events"]];
const galleryItems = [["Photo gallery", "/photo-gallery"], ["Video sermons", "/sermons"]];
const logoUrl = "https://res.cloudinary.com/hularox3/image/upload/q_auto:best,f_auto,w_1600/tlgom/branding/logo.png"; const goImageUrl = "/go.png";
type SectionId = "welcome" | "battle-cry" | "featured-sermons" | "upcoming-events" | "gallery" | "submissions";
const defaultOrder: SectionId[] = ["welcome", "battle-cry", "featured-sermons", "upcoming-events", "gallery", "submissions"]; const defaultVisibility: Record<SectionId, boolean> = { welcome:true, "battle-cry":true, "featured-sermons":true, "upcoming-events":true, gallery:true, submissions:true };
type SectionContent = { welcomeKicker:string; welcomeHeading:string; welcomeLead:string; battleKicker:string; battleQuote:string; battleReference:string; scriptureKicker:string; scriptureQuote:string; scriptureReference:string };
const defaultContent: SectionContent = { welcomeKicker:"Welcome to The Life Global Outreach Ministries", welcomeHeading:"A Global Mission.", welcomeLead:"TLGOM is a ministry focused on leading people to Christ massively, worldwide, and establishing them in the Word of God.", battleKicker:"Our battle cry", battleQuote:"There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.", battleReference:"Romans 8:1", scriptureKicker:"Our scripture", scriptureQuote:"Jesus Christ the same yesterday, and to day, and for ever.", scriptureReference:"Hebrews 13:8" };
function imageUrl(url:string) { return url.includes("/upload/") && !url.includes("q_auto") ? url.replace("/upload/","/upload/q_auto:best,f_auto,w_1600/") : url; }

export default function Home() {
  const [activeSlide, setActiveSlide] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [galleryOpen, setGalleryOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [viewportWidth, setViewportWidth] = useState(0); const [slides, setSlides] = useState<SlideshowImage[]>([]); const [order, setOrder] = useState(defaultOrder); const [visibility, setVisibility] = useState(defaultVisibility); const [sermons, setSermons] = useState<Sermon[]>([]); const [events, setEvents] = useState<ChurchEvent[]>([]); const [albums, setAlbums] = useState<GalleryAlbum[]>([]); const [photos, setPhotos] = useState<GalleryPhoto[]>([]); const [now, setNow] = useState(() => new Date()); const [content, setContent] = useState(defaultContent); const [submissionContent, setSubmissionContent] = useState<SubmissionContent>({ title: "There is room for your story.", description: "Whether you need prayer or want to share what God has done, we are ready to listen." });
  const galleryRef = useRef<HTMLDivElement>(null); const touchStartX = useRef<number | null>(null);
  useEffect(() => { const resize = () => setViewportWidth(window.innerWidth); const scroll = () => setScrolled(window.scrollY > 12); resize(); scroll(); window.addEventListener("resize", resize, { passive: true }); window.addEventListener("scroll", scroll, { passive: true }); return () => { window.removeEventListener("resize", resize); window.removeEventListener("scroll", scroll); }; }, []);
  useEffect(() => { const close = (event: PointerEvent) => { if (galleryRef.current && !galleryRef.current.contains(event.target as Node)) setGalleryOpen(false); }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, []);
  useEffect(()=>{if(!db)return; const a=onSnapshot(collection(db,"slideshow"),s=>{setSlides(s.docs.map(i=>({id:i.id,...i.data()} as SlideshowImage)).filter(i=>i.enabled!==false).sort((a,b)=>a.order-b.order));setActiveSlide(0);}); const b=onSnapshot(collection(db,"sermons"),s=>setSermons(s.docs.map(i=>({id:i.id,...i.data()} as Sermon)).filter(i=>i.enabled!==false).sort((a,b)=>(a.order??0)-(b.order??0)))); const c=onSnapshot(collection(db,"events"),s=>setEvents(s.docs.map(i=>({id:i.id,...i.data()} as ChurchEvent)).filter(i=>i.enabled!==false))); const d=onSnapshot(collection(db,"galleryAlbums"),s=>setAlbums(s.docs.map(i=>({id:i.id,...i.data()} as GalleryAlbum)).filter(i=>i.visible!==false).sort((a,b)=>(a.order||0)-(b.order||0)))); const e=onSnapshot(collection(db,"galleryPhotos"),s=>setPhotos(s.docs.map(i=>({id:i.id,...i.data()} as GalleryPhoto)).filter(i=>i.visible!==false))); return()=>{a();b();c();d();e();};},[]);
  useEffect(()=>{if(!db)return; return onSnapshot(doc(db,"siteSettings","homepage"),s=>{const data=s.data(); if(Array.isArray(data?.sectionOrder)){const valid=data.sectionOrder.filter((i):i is SectionId=>defaultOrder.includes(i));setOrder([...valid,...defaultOrder.filter(i=>!valid.includes(i))]);} if(data?.sectionVisibility&&typeof data.sectionVisibility==="object")setVisibility({...defaultVisibility,...data.sectionVisibility}); if(data?.sectionContent&&typeof data.sectionContent==="object")setContent({...defaultContent,...data.sectionContent}); const sub=data?.submissionContent; if(sub&&typeof sub==="object")setSubmissionContent(current=>({...current,...sub}));});},[]);
  const legacy = (slide: SlideshowImage) => !slide.desktopImageUrl && !slide.tabletImageUrl && !slide.mobileImageUrl && Boolean(slide.imageUrl);
  const desktopSlides = slides.filter((slide) => slide.desktopImageUrl || legacy(slide)); const tabletSlides = slides.filter((slide) => slide.tabletImageUrl || legacy(slide)); const mobileSlides = slides.filter((slide) => slide.mobileImageUrl || legacy(slide));
  const visibleSlides = viewportWidth > 0 && viewportWidth <= 760 ? mobileSlides : viewportWidth > 0 && viewportWidth <= 1050 ? tabletSlides : desktopSlides;
  useEffect(() => { if (!visibleSlides.length) return; const timer = window.setInterval(() => setActiveSlide((current) => (current + 1) % visibleSlides.length), 6500); return () => window.clearInterval(timer); }, [visibleSlides.length]);
  useEffect(() => { const handleTouchStart = (event: TouchEvent) => { if ((event.target as HTMLElement).closest(".hero-page")) touchStartX.current = event.changedTouches[0]?.clientX ?? null; }; const handleTouchEnd = (event: TouchEvent) => { if (touchStartX.current === null || !visibleSlides.length || !(event.target as HTMLElement).closest(".hero-page")) return; const distance = event.changedTouches[0].clientX - touchStartX.current; if (Math.abs(distance) > 50) setActiveSlide((current) => (current + (distance < 0 ? 1 : -1) + visibleSlides.length) % visibleSlides.length); touchStartX.current = null; }; document.addEventListener("touchstart", handleTouchStart, { passive: true }); document.addEventListener("touchend", handleTouchEnd, { passive: true }); return () => { document.removeEventListener("touchstart", handleTouchStart); document.removeEventListener("touchend", handleTouchEnd); }; }, [visibleSlides.length]);
  const closeMenus = () => { setMenuOpen(false); setGalleryOpen(false); };
  const renderTrack = (items: SlideshowImage[], className: string, imageKey: "desktopImageUrl" | "tabletImageUrl" | "mobileImageUrl") => { const activeIndex = items.findIndex((slide) => slide.id === visibleSlides[activeSlide % Math.max(visibleSlides.length, 1)]?.id); return <div className={`hero-background-track ${className}`} style={{ transform: `translateX(-${items.length && activeIndex >= 0 ? activeIndex * 100 : 0}%)` }}>{items.map((slide) => <div className="hero-background" key={`${className}-${slide.id}`}><div className="hero-background-image" style={{ backgroundImage: `url("${imageUrl(slide[imageKey] || (legacy(slide) ? slide.imageUrl : "") || "")}")` }} /></div>)}</div>; };
  const welcome=<section className="welcome-section"><div className="container welcome-grid"><div className="welcome-visual"><div className="welcome-image-frame"><Image src={goImageUrl} alt="Rev'd Dr. Joseph Ola, General Overseer" fill sizes="(max-width:760px) 90vw,45vw"/></div><div className="welcome-caption">Rev'd Dr. Joseph Ola<br/><small>General Overseer</small></div></div><div className="welcome-copy"><p className="section-kicker">{content.welcomeKicker}</p><h2><em>{content.welcomeHeading}</em></h2><p className="welcome-lead">{content.welcomeLead}</p><Link className="welcome-link" href="/about-us">Discover our story <ArrowRight size={17}/></Link></div></div></section>;
  const battle=<section className="battle-cry-section"><div className="battle-cry-glow"/><div className="container battle-cry-inner"><div className="battle-cry-panel"><p className="section-kicker">{content.battleKicker}</p><span className="battle-cry-reference">{content.battleReference}</span><blockquote>{content.battleQuote}</blockquote></div><div className="battle-cry-panel"><p className="section-kicker">{content.scriptureKicker}</p><span className="battle-cry-reference">{content.scriptureReference}</span><blockquote>{content.scriptureQuote}</blockquote></div><span className="battle-cry-mark">8:1</span></div></section>;
  const sermonCards=sermons.slice(0,3); const sermonsSection=<section className="featured-sermons-section"><div className="container"><div className="featured-sermons-heading"><div><p className="section-kicker">From the archive</p><h2>Video sermons</h2></div></div><div className="sermon-cards">{sermonCards.map(s=><SermonCard sermon={s} key={s.id}/>)}<Link className="sermon-card view-all-card" href="/sermons"><strong>View all sermons</strong><small>Explore the full archive</small><ArrowRight size={19}/></Link></div></div></section>;
  const upcoming=events.map(event=>({event,start:getNextEventDate(event,now)})).filter((x):x is {event:ChurchEvent;start:Date}=>Boolean(x.start)).sort((a,b)=>a.start.getTime()-b.start.getTime()).slice(0,3); const eventsSection=<section className="upcoming-events-section"><div className="container"><div className="upcoming-events-heading"><div><p className="section-kicker">Gather with us</p><h2>Upcoming events</h2></div></div>{upcoming.length?<div className="event-cards">{upcoming.map(x=><EventCard event={x.event} start={x.start} now={now} key={x.event.id}/>)}<Link className="event-card view-all-event-card" href="/events"><strong>View more events</strong><small>See the complete church calendar</small><ArrowRight size={19}/></Link></div>:<div className="no-events-message"><h3>No upcoming events</h3></div>}</div></section>;
  const sections = { welcome, "battle-cry": battle, "featured-sermons": sermonsSection, "upcoming-events": eventsSection, gallery: <HomepageGallerySection albums={albums} photos={photos}/>, submissions: <SubmissionForms content={submissionContent}/> } satisfies Record<SectionId, ReactNode>;
  return <><main className={`hero-page ${slides.length ? "has-slides" : "no-slides"}`}>{renderTrack(desktopSlides, "desktop-track", "desktopImageUrl")}{renderTrack(tabletSlides, "tablet-track", "tabletImageUrl")}{renderTrack(mobileSlides, "mobile-track", "mobileImageUrl")}<div className="hero-shade" aria-hidden="true" /><header className={`site-header hero-header ${scrolled ? "is-scrolled" : ""}`}><div className="container header-inner"><Link className="header-brand" href="/" aria-label="TLGOM home"><Image src={logoUrl} alt="The Life Global Outreach Ministries logo" width={50} height={50} priority /><span><strong>THE LIFE GLOBAL</strong><small>OUTREACH MINISTRIES</small></span></Link><nav className={`desktop-nav ${menuOpen ? "mobile-open" : ""}`} aria-label="Main navigation">{navItems.map(([label, href], index) => <a className={index === 0 ? "active" : ""} href={href} key={label} onClick={closeMenus}>{label}</a>)}<div className={`nav-dropdown ${galleryOpen ? "open" : ""}`} ref={galleryRef}><button className="nav-dropdown-trigger" onClick={() => { if (window.innerWidth <= 760) setGalleryOpen(!galleryOpen); }} aria-expanded={galleryOpen}>Gallery <ChevronDown size={15} /></button><div className="nav-dropdown-menu">{galleryItems.map(([label, href]) => <a href={href} key={label} onClick={closeMenus}>{label}</a>)}</div></div></nav><a className="give-button" href="/give">Give/Tithe</a><button className="menu-button hero-menu" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={23} /> : <Menu size={23} />}</button></div></header><Link className="hero-logo" href="/" aria-label="TLGOM home"><span className="logo-ring" aria-hidden="true" /><span className="logo-background"><span className="logo-background-text">TLGOM logo background</span></span><Image src={logoUrl} alt="The Life Global Outreach Ministries logo" width={76} height={76} priority /></Link><section className="hero-content"><div className="container hero-content-inner"><div className="hero-actions"><a className="hero-button primary" href="/about-us">Discover the ministry <ArrowRight size={18} /></a><a className="hero-button secondary" href="/#prayer-testimony">Need a prayer ?</a></div></div></section>{visibleSlides.length > 1 && <div className="slide-controls" aria-label="Hero slides">{visibleSlides.map((slide, index) => <button className={index === activeSlide % visibleSlides.length ? "selected" : ""} key={slide.id} aria-label={`Show slide ${index + 1}`} aria-pressed={index === activeSlide % visibleSlides.length} onClick={() => setActiveSlide(index)} />)}</div>}</main>{order.filter(section => visibility[section]).map(section => <div key={section}>{sections[section]}</div>)}<SiteFooter /></>;
}
