"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { addDoc, collection, deleteDoc, doc, onSnapshot, serverTimestamp, setDoc, updateDoc } from "firebase/firestore";
import { onAuthStateChanged, type User } from "firebase/auth";
import { ArrowLeft, Edit3, Eye, EyeOff, GripVertical, LoaderCircle, Plus, Save, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { auth, db, firebaseReady } from "@/lib/firebase/client";
import { defaultAboutContent, emptyLeader, leaderSlug, roleInfo, type AboutContent, type Leader, type LeadershipCategory } from "@/lib/about";

type SocialKey = "website" | "facebook" | "instagram" | "youtube" | "linkedin";
const socialFields: { key: SocialKey; label: string; placeholder: string }[] = [
  { key: "website", label: "Website URL", placeholder: "https://..." },
  { key: "facebook", label: "Facebook URL", placeholder: "https://facebook.com/..." },
  { key: "instagram", label: "Instagram URL", placeholder: "https://instagram.com/..." },
  { key: "youtube", label: "YouTube URL", placeholder: "https://youtube.com/..." },
  { key: "linkedin", label: "LinkedIn URL", placeholder: "https://linkedin.com/..." },
];
const emptyCategory = (): LeadershipCategory => ({ id: "", name: "", slug: "", rank: 1, published: true });
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function uploadPortrait(file: File, token: string) {
  const signed = await fetch("/api/cloudinary/sign", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ folder: "tlgom/about" }) });
  const signature = await signed.json();
  if (!signed.ok) throw new Error(signature.error || "Could not authorize portrait upload.");
  const form = new FormData();
  form.append("file", file); form.append("api_key", signature.apiKey); form.append("timestamp", signature.timestamp); form.append("folder", signature.folder); form.append("signature", signature.signature);
  const response = await fetch(`https://api.cloudinary.com/v1_1/${signature.cloudName}/image/upload`, { method: "POST", body: form });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error?.message || "Portrait upload failed.");
  return { url: result.secure_url as string, publicId: result.public_id as string };
}

export default function AboutAdminPage() {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false);
  const [content, setContent] = useState<AboutContent>(defaultAboutContent); const [leaders, setLeaders] = useState<Leader[]>([]); const [categories, setCategories] = useState<LeadershipCategory[]>([]);
  const [editing, setEditing] = useState<Leader | null>(null); const [category, setCategory] = useState<LeadershipCategory | null>(null); const [dragged, setDragged] = useState<string | null>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, (next) => { setUser(next); setReady(true); }); }, []);
  useEffect(() => { if (ready && !user) router.replace("/control-room?next=/control-room/about"); }, [ready, user, router]);
  useEffect(() => { if (!db || !user) return; const stopAbout = onSnapshot(doc(db, "siteSettings", "about"), (snap) => setContent({ ...defaultAboutContent, ...(snap.data() || {}) })); const stopLeaders = onSnapshot(collection(db, "leadership"), (snap) => setLeaders(snap.docs.map((item) => ({ id: item.id, ...item.data() } as Leader)).sort((a, b) => a.order - b.order)); const stopCategories = onSnapshot(collection(db, "leadershipCategories"), (snap) => setCategories(snap.docs.map((item) => ({ id: item.id, ...item.data() } as LeadershipCategory)).sort((a, b) => a.rank - b.rank)); return () => { stopAbout(); stopLeaders(); stopCategories(); }; }, [user]);
  const groups = useMemo(() => [{ id: "", name: "Uncategorized", rank: 9999 }, ...categories].map((item) => ({ ...item, leaders: leaders.filter((leader) => (leader.categoryId || "") === item.id).sort((a, b) => a.order - b.order || a.name.localeCompare(b.name)) })).filter((item) => item.id || item.leaders.length), [categories, leaders]);
  const updateLeader = (key: keyof Leader, value: string | number | boolean) => setEditing((current) => current ? { ...current, [key]: value } : current);
  const updateSocial = (key: SocialKey, value: string) => setEditing((current) => current ? { ...current, socialLinks: { ...(current.socialLinks || {}), [key]: value } } : current);
  async function deletePortrait(publicId?: string) { if (!publicId || !user) return; const response = await fetch("/api/cloudinary/delete", { method: "POST", headers: { Authorization: `Bearer ${await user.getIdToken()}`, "Content-Type": "application/json" }, body: JSON.stringify({ assets: [{ publicId, resourceType: "image" }] }) }); if (!response.ok) throw new Error("Could not delete the Cloudinary portrait."); }
  async function saveContent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!db) return; setBusy(true); setError(""); try { await setDoc(doc(db, "siteSettings", "about"), { ...content, updatedAt: serverTimestamp() }, { merge: true }); setMessage("About page content saved."); } catch { setError("Could not save About page content."); } finally { setBusy(false); } }
  async function saveCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!db || !category) return; setBusy(true); setError(""); try { const data = { name: category.name.trim(), slug: slugify(category.slug || category.name), rank: Number(category.rank) || 0, published: category.published !== false, updatedAt: serverTimestamp() }; if (!data.name) throw new Error("Add a category name."); if (category.id) await updateDoc(doc(db, "leadershipCategories", category.id), data); else await addDoc(collection(db, "leadershipCategories"), { ...data, createdAt: serverTimestamp() }); setCategory(null); setMessage("Leadership category saved."); } catch (issue) { setError(issue instanceof Error ? issue.message : "Could not save category."); } finally { setBusy(false); } }
  async function saveLeader(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!db || !user || !editing) return; setBusy(true); setError(""); let uploaded: { url: string; publicId: string } | null = null; try { const file = new FormData(event.currentTarget).get("photo"); uploaded = file instanceof File && file.size ? await uploadPortrait(file, await user.getIdToken()) : null; if (!editing.name.trim()) throw new Error("Add the leader's name."); const { id: _id, ...fields } = editing; const data = { ...fields, name: editing.name.trim(), slug: editing.slug.trim() || leaderSlug(editing.name), role: editing.role.trim(), categoryId: editing.categoryId || "", ministry: editing.ministry?.trim() || "", photoUrl: uploaded?.url || editing.photoUrl, photoPublicId: uploaded?.publicId || editing.photoPublicId || "", photoAlt: editing.photoAlt.trim(), shortBio: editing.shortBio.trim(), biography: editing.biography.trim(), socialLinks: Object.fromEntries(Object.entries(editing.socialLinks || {}).filter(([, value]) => value.trim())), order: Number(editing.order) || 0, updatedAt: serverTimestamp() }; if (editing.id) await updateDoc(doc(db, "leadership", editing.id), data); else await addDoc(collection(db, "leadership"), { ...data, createdAt: serverTimestamp() }); if (uploaded && editing.photoPublicId && editing.photoPublicId !== uploaded.publicId) await deletePortrait(editing.photoPublicId); setEditing(null); setMessage("Leader saved."); } catch (issue) { if (uploaded) await deletePortrait(uploaded.publicId).catch(() => undefined); setError(issue instanceof Error ? issue.message : "Could not save leader."); } finally { setBusy(false); } }
  async function removeLeader(leader: Leader) { if (!db || !window.confirm(`Delete ${leader.name}? Their uploaded portrait will also be removed from Cloudinary.`)) return; setBusy(true); setError(""); try { await deletePortrait(leader.photoPublicId); await deleteDoc(doc(db, "leadership", leader.id)); setMessage("Leader and portrait deleted."); } catch (issue) { setError(issue instanceof Error ? issue.message : "Could not delete leader."); } finally { setBusy(false); } }
  async function reorder(categoryId: string, targetId: string) { if (!db || !dragged || dragged === targetId) return; const group = groups.find((item) => item.id === categoryId)?.leaders || []; const from = group.findIndex((item) => item.id === dragged); const to = group.findIndex((item) => item.id === targetId); if (from < 0 || to < 0) return; const next = [...group]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); await Promise.all(next.map((leader, index) => updateDoc(doc(db!, "leadership", leader.id), { order: index, updatedAt: serverTimestamp() }))); setDragged(null); setMessage("Card order saved."); }
  if (!firebaseReady || !ready || !user) return <main className="login-page"><LoaderCircle className="spin" size={28} /></main>;
  return <main className="admin-page"><section className="admin-content"><Link className="admin-back" href="/control-room"><ArrowLeft size={16} /> Back to Control Room</Link><div className="admin-topbar"><div><p className="admin-kicker">About page</p><h1>About and leadership</h1><p className="admin-intro">Manage mission, vision, leadership profiles, categories, ordering, ministry assignment, and public links.</p></div></div>{message && <div className="admin-notice success">{message}</div>}{error && <div className="admin-notice error">{error}</div>}
  <form className="sermon-form" onSubmit={saveContent}><div className="upload-title"><Edit3 size={19} /><div><h2>About page content</h2><p>These fields control the mission, vision, legacy, and story sections.</p></div></div><div className="sermon-form-grid"><label className="wide-field">Introduction<textarea value={content.intro} onChange={(e) => setContent({ ...content, intro: e.target.value })} /></label><label>Mission<textarea value={content.mission} onChange={(e) => setContent({ ...content, mission: e.target.value })} /></label><label>Vision<textarea value={content.vision} onChange={(e) => setContent({ ...content, vision: e.target.value })} /></label><label>Legacy heading<input value={content.legacyTitle} onChange={(e) => setContent({ ...content, legacyTitle: e.target.value })} /></label><label>Legacy content<textarea value={content.legacyText} onChange={(e) => setContent({ ...content, legacyText: e.target.value })} /></label><label>Story heading<input value={content.storyTitle} onChange={(e) => setContent({ ...content, storyTitle: e.target.value })} /></label><label>Story content<textarea value={content.storyText} onChange={(e) => setContent({ ...content, storyText: e.target.value })} /></label></div><button className="admin-button" disabled={busy}><Save size={17} /> Save About content</button></form>
  <section className="article-editor-section"><div className="slides-header"><div><p className="admin-kicker">Leadership categories</p><h2>Create and rank categories</h2><p>Drag leader cards within each category to save their order.</p></div><button type="button" className="admin-button" onClick={() => setCategory(emptyCategory())}><Plus size={17} /> Add category</button></div><div className="blog-admin-list">{categories.map((item) => <article className="blog-admin-row" key={item.id}><div><strong>{item.name}</strong><small>Rank {item.rank} · {item.published ? "Published" : "Hidden"}</small></div><button type="button" title="Edit category" onClick={() => setCategory(item)}><Edit3 size={17} /></button><button type="button" title="Delete category" onClick={() => deleteDoc(doc(db!, "leadershipCategories", item.id))}><Trash2 size={17} /></button></article>)}</div>{category && <form className="sermon-form" onSubmit={saveCategory}><div className="upload-title"><Edit3 size={19} /><div><h2>{category.id ? "Edit category" : "New category"}</h2><p>Lower rank numbers appear first publicly.</p></div><button className="icon-close-button" type="button" onClick={() => setCategory(null)}><X size={18} /></button></div><div className="sermon-form-grid"><label>Category name<input required value={category.name} onChange={(e) => setCategory({ ...category, name: e.target.value })} /></label><label>Rank<input type="number" min="0" value={category.rank} onChange={(e) => setCategory({ ...category, rank: Number(e.target.value) })} /></label><label>Slug<input value={category.slug} onChange={(e) => setCategory({ ...category, slug: e.target.value })} /></label></div><button className="admin-button" disabled={busy}><Save size={17} /> Save category</button></form>}</section>
  <section className="article-editor-section"><div className="slides-header"><div><p className="admin-kicker">Leadership cards</p><h2>{leaders.length} {leaders.length === 1 ? "leader" : "leaders"}</h2></div></div>{groups.map((group) => <div className="leadership-admin-group" key={group.id || "uncategorized"}><div className="slides-header"><div><h3>{group.name}</h3><p>Drag cards to reorder this category.</p></div></div><div className="blog-admin-list">{group.leaders.map((leader) => <article className="blog-admin-row leadership-admin-row" key={leader.id} draggable onDragStart={() => setDragged(leader.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => reorder(group.id, leader.id)}><GripVertical className="leadership-drag-handle" size={19} /><div>{leader.photoUrl && <img src={leader.photoUrl} alt="" />}<strong>{leader.name}</strong><small>{leader.role || roleInfo(leader.role).label} · Card order {leader.order} · {leader.published ? "Published" : "Hidden"}</small></div><button type="button" title={leader.published ? "Unpublish" : "Publish"} onClick={() => updateDoc(doc(db!, "leadership", leader.id), { published: !leader.published })}>{leader.published ? <Eye size={17} /> : <EyeOff size={17} />}</button><button type="button" title="Edit leader" onClick={() => setEditing({ ...leader, socialLinks: leader.socialLinks || {} })}><Edit3 size={17} /></button><button type="button" title="Delete leader" onClick={() => removeLeader(leader)}><Trash2 size={17} /></button></article>)}</div></div>)}<button type="button" className="admin-button" onClick={() => setEditing(emptyLeader())}><Plus size={17} /> Add leader</button>
  {editing && <form className="sermon-form edit-sermon-form" onSubmit={saveLeader}><div className="upload-title"><Edit3 size={19} /><div><h2>{editing.id ? "Edit leader" : "Add leader"}</h2><p>Published leaders can have a public profile at /about/leadership/{editing.slug || "leader-name"}.</p></div><button className="icon-close-button" type="button" onClick={() => setEditing(null)}><X size={18} /></button></div><div className="sermon-form-grid"><label>Full name<input required value={editing.name} onChange={(e) => updateLeader("name", e.target.value)} /></label><label>Public profile slug<input value={editing.slug} onChange={(e) => updateLeader("slug", slugify(e.target.value))} placeholder={leaderSlug(editing.name) || "leader-name"} /></label><label>Official role<input value={editing.role} onChange={(e) => updateLeader("role", e.target.value)} placeholder="Pastor, General Overseer, Choir Director" /></label><label>Leadership category<select value={editing.categoryId || ""} onChange={(e) => updateLeader("categoryId", e.target.value)}><option value="">Uncategorized</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name} · Rank {item.rank}</option>)}</select></label><label>Ministry / department<input value={editing.ministry || ""} onChange={(e) => updateLeader("ministry", e.target.value)} placeholder="e.g. Prayer Ministry" /></label><label>Card order<input type="number" value={editing.order} onChange={(e) => updateLeader("order", Number(e.target.value))} /></label><label>Portrait image<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" /></label><label>Portrait URL<input value={editing.photoUrl} onChange={(e) => updateLeader("photoUrl", e.target.value)} placeholder="Optional Cloudinary URL" /></label><label>Portrait alt text<input value={editing.photoAlt} onChange={(e) => updateLeader("photoAlt", e.target.value)} /></label>{socialFields.map((field) => <label key={field.key}>{field.label}<input type="url" value={editing.socialLinks?.[field.key] || ""} onChange={(e) => updateSocial(field.key, e.target.value)} placeholder={field.placeholder} /></label>)}<label className="wide-field">Short biography<textarea value={editing.shortBio} onChange={(e) => updateLeader("shortBio", e.target.value)} /></label><label className="wide-field">Full biography / public profile<textarea value={editing.biography} onChange={(e) => updateLeader("biography", e.target.value)} /></label></div><label className="recurring-toggle"><input type="checkbox" checked={editing.published} onChange={(e) => updateLeader("published", e.target.checked)} /><span><strong>Publish this leader</strong><small>Published leaders appear on About TLGOM and their profile is public.</small></span></label><button className="admin-button" disabled={busy}>{busy ? "Saving..." : "Save leader"}</button></form>}</section></section></main>;
}
