"use client";

import { FormEvent, useState } from "react";
import { Facebook, Instagram, LoaderCircle, MessageCircle, Send, Twitter, Youtube } from "lucide-react";
import type { ContactSettings } from "@/lib/contact";

const socialLinks = (contact: ContactSettings) => [["Facebook", contact.socialLinks?.facebook, Facebook], ["Instagram", contact.socialLinks?.instagram, Instagram], ["YouTube", contact.socialLinks?.youtube, Youtube], ["X", contact.socialLinks?.x, Twitter], ["WhatsApp", contact.socialLinks?.whatsapp, MessageCircle]] as const;

export default function ContactPageClient({ contact }: { contact: ContactSettings }) {
  const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); setError(""); try { const response = await fetch("/api/submissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "contact", name: data.get("name"), email: data.get("email"), phone: data.get("phone"), location: data.get("location"), subject: data.get("subject"), message: data.get("message") }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not send your message."); form.reset(); setSent(true); } catch (issue) { setError(issue instanceof Error ? issue.message : "Could not send your message."); } finally { setBusy(false); } }
  const socials = socialLinks(contact).filter((item) => item[1]);
  return <><section className="contact-hero"><div className="container"><p className="section-kicker">Get in touch</p><h1>Contact us</h1><p>We would be glad to hear from you. Send us a message and our team will get back to you.</p></div></section><section className="contact-content"><div className="container contact-grid"><div className="contact-details"><p className="section-kicker">Reach TLGOM</p><h2>We are here to listen.</h2><p>For questions, ministry information, prayer, or partnership, contact us through any of the details below.</p><div className="contact-detail-list"><div><strong>EMAIL</strong>{contact.emails.length ? contact.emails.map((email) => <a href={`mailto:${email}`} key={email}>{email}</a>) : <span>Contact details will be shared soon.</span>}</div><div><strong>PHONE</strong>{contact.phones.length ? contact.phones.map((phone) => <a href={`tel:${phone.replace(/\s+/g, "")}`} key={phone}>{phone}</a>) : <span>Contact details will be shared soon.</span>}</div><div><strong>LOCATION</strong><span>2, Onadairo Street, Abule-Ijoko, Ogun State</span></div>{contact.serviceTimes.length > 0 && <div><strong>SERVICE TIMES</strong>{contact.serviceTimes.map((time) => <span key={time}>{time}</span>)}</div>}{socials.length > 0 && <div><strong>FOLLOW TLGOM</strong><div className="contact-social-links">{socials.map(([label, url, Icon]) => <a href={url!} target="_blank" rel="noreferrer" aria-label={"Follow TLGOM on " + label} key={label}><Icon size={17} /><span>{label}</span></a>)}</div></div>}</div></div><div className="contact-form-card">{sent ? <div className="submission-success"><h3>Message sent.</h3><p>Thank you for contacting The Life Global Outreach Ministries. We will get back to you.</p><button type="button" className="submission-reset" onClick={() => setSent(false)}>Send another message</button></div> : <form onSubmit={submit}><label>Your Name <span className="required-label">(required)</span><input name="name" required /></label><label>Your Email <span className="required-label">(required)</span><input name="email" type="email" required /></label><label>Mobile Number <span className="required-label">(required)</span><input name="phone" type="tel" required /></label><label>Location <span className="required-label">(required)</span><input name="location" required /></label><label>Subject <span className="required-label">(required)</span><input name="subject" required /></label><label>Your Message<textarea name="message" required minLength={10} rows={7} /></label>{error && <p className="submission-error">{error}</p>}<button className="admin-button submission-submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <Send size={17} />} {busy ? "Sending..." : "Send message"}</button></form>}</div></div></section></>;
}
