"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Images, LoaderCircle } from "lucide-react";
import { collection, onSnapshot } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import type { GalleryAlbum, GalleryPhoto } from "@/lib/gallery";

export default function GalleryBrowser({ slug }: { slug?: string }) {
  const [albums, setAlbums] = useState<GalleryAlbum[]>([]); const [photos, setPhotos] = useState<GalleryPhoto[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!db) { setLoading(false); return; } const stopAlbums = onSnapshot(collection(db, "galleryAlbums"), (snapshot) => { setAlbums(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as GalleryAlbum)).filter((item) => item.visible !== false).sort((a, b) => (a.order || 0) - (b.order || 0))); setLoading(false); }); const stopPhotos = onSnapshot(collection(db, "galleryPhotos"), (snapshot) => setPhotos(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as GalleryPhoto)).filter((item) => item.visible !== false).sort((a, b) => (a.order || 0) - (b.order || 0)))); return () => { stopAlbums(); stopPhotos(); }; }, []);
  const album = slug ? albums.find((item) => item.slug === slug) : undefined; const children = albums.filter((item) => (album ? item.parentId === album.id : !item.parentId)); const albumPhotos = album ? photos.filter((item) => item.albumId === album.id) : [];
  const coverFor = (item: GalleryAlbum): string => { if (item.coverImageUrl) return item.coverImageUrl; const ownPhoto = photos.find((photo) => photo.albumId === item.id); if (ownPhoto) return ownPhoto.imageUrl; const child = albums.find((candidate) => candidate.parentId === item.id); return child ? coverFor(child) : ""; };
  const parent = album?.parentId ? albums.find((item) => item.id === album.parentId) : undefined;
  if (loading) return <main className="gallery-page"><LoaderCircle className="spin" size={28} /></main>;
  if (slug && !album) return <main className="gallery-page"><div className="container gallery-empty"><h1>Album not found</h1><Link href="/photo-gallery">Return to photo gallery</Link></div></main>;
  return <main className="gallery-page"><section className="gallery-hero"><div className="container"><p className="section-kicker">The TLGOM archive</p><h1>{album?.name || "Photo gallery"}</h1><p>{album?.description || "Moments, milestones, and memories from the life of the ministry."}</p></div></section><section className="gallery-content"><div className="container">{album && <Link className="gallery-back" href={parent ? `/photo-gallery/${parent.slug}` : "/photo-gallery"}><ArrowLeft size={15} /> Back to {parent?.name || "Photo gallery"}</Link>}{children.length > 0 && <><div className="gallery-subheading"><p className="section-kicker">Collections</p><h2>{album ? "Inside this album" : "Explore the archive"}</h2></div><div className="album-grid">{children.map((child) => <Link className="album-card" href={`/photo-gallery/${child.slug}`} key={child.id}><div className="album-cover" style={{ backgroundImage: coverFor(child) ? `url("${coverFor(child)}")` : undefined }}><Images size={22} /></div><div><h3>{child.name}</h3><p>{child.description || "View album"}</p></div><ArrowRight size={17} /></Link>)}</div></>}{album && <div className="gallery-photos"><div className="gallery-subheading"><p className="section-kicker">Photographs</p><h2>{albumPhotos.length ? `${albumPhotos.length} ${albumPhotos.length === 1 ? "photo" : "photos"}` : "No images yet"}</h2></div>{albumPhotos.length ? <div className="photo-grid">{albumPhotos.map((photo) => <div className="photo-tile" key={photo.id}><img src={photo.imageUrl} alt={photo.alt || album.name} /></div>)}</div> : <div className="gallery-empty"><Images size={28} /><p>No images yet under this album.</p></div>}</div>}{!album && !children.length && <div className="gallery-empty"><Images size={28} /><p>No albums yet. Check back soon.</p></div>}</div></section></main>;
}
