"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ChevronDown, Images, LoaderCircle, X } from "lucide-react";
import { collection, onSnapshot } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import type { GalleryAlbum, GalleryPhoto } from "@/lib/gallery";

function shortDescription(description?: string) { const text = (description || "View this album").trim(); return text.length > 90 ? `${text.slice(0, 90).trimEnd()}…` : text; }

export default function GalleryBrowser({ slug }: { slug?: string }) {
  const [albums, setAlbums] = useState<GalleryAlbum[]>([]); const [photos, setPhotos] = useState<GalleryPhoto[]>([]); const [loading, setLoading] = useState(true); const [lightbox, setLightbox] = useState<number | null>(null); const touchStart = useRef<number | null>(null);
  useEffect(() => { if (!db) { setLoading(false); return; } const stopAlbums = onSnapshot(collection(db, "galleryAlbums"), (snapshot) => { setAlbums(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as GalleryAlbum)).filter((item) => item.visible !== false).sort((a, b) => (a.order || 0) - (b.order || 0))); setLoading(false); }); const stopPhotos = onSnapshot(collection(db, "galleryPhotos"), (snapshot) => setPhotos(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as GalleryPhoto)).filter((item) => item.visible !== false).sort((a, b) => (a.order || 0) - (b.order || 0)))); return () => { stopAlbums(); stopPhotos(); }; }, []);
  const album = slug ? albums.find((item) => item.slug === slug) : undefined; const albumName = album?.name || "Photo gallery"; const children = albums.filter((item) => (album ? item.parentId === album.id : !item.parentId)); const albumPhotos = album ? photos.filter((item) => item.albumId === album.id) : []; const parent = album?.parentId ? albums.find((item) => item.id === album.parentId) : undefined;
  const coverFor = (item: GalleryAlbum): string => { if (item.coverImageUrl) return item.coverImageUrl; const ownPhoto = photos.find((photo) => photo.albumId === item.id); if (ownPhoto) return ownPhoto.imageUrl; const child = albums.find((candidate) => candidate.parentId === item.id); return child ? coverFor(child) : ""; };
  const goPhoto = (direction: -1 | 1) => setLightbox((current) => current === null ? null : (current + direction + albumPhotos.length) % albumPhotos.length);
  function AlbumCard({ item }: { item: GalleryAlbum }) { const nested = albums.filter((candidate) => candidate.parentId === item.id); return <details className="album-dropdown"><summary><div className="album-card"><div className="album-cover" style={{ backgroundImage: coverFor(item) ? `url("${coverFor(item)}")` : undefined }}>{!coverFor(item) && <Images size={22} />}</div><div><h3>{item.name}</h3><p>{shortDescription(item.description)}</p></div><ChevronDown className="album-chevron" size={18} /></div></summary>{nested.length > 0 && <div className="album-dropdown-children">{nested.map((child) => <AlbumCard item={child} key={child.id} />)}</div>}</details>; }
  useEffect(() => { if (lightbox === null) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setLightbox(null); if (event.key === "ArrowLeft") goPhoto(-1); if (event.key === "ArrowRight") goPhoto(1); }; window.addEventListener("keydown", close); document.body.style.overflow = "hidden"; return () => { window.removeEventListener("keydown", close); document.body.style.overflow = ""; }; }, [lightbox]);
  if (loading) return <main className="gallery-page"><LoaderCircle className="spin" size={28} /></main>;
  if (slug && !album) return <main className="gallery-page"><div className="container gallery-empty"><h1>Album not found</h1><Link href="/photo-gallery">Return to photo gallery</Link></div></main>;
  return <main className="gallery-page"><section className="gallery-hero"><div className="container"><p className="section-kicker">The TLGOM archive</p><h1>{albumName}</h1><p>{album ? album.description || "Explore this collection from the life of the ministry." : "Moments, milestones, and memories from the life of the ministry."}</p></div></section><section className="gallery-content"><div className="container">{album && <Link className="gallery-back" href={parent ? `/photo-gallery/${parent.slug}` : "/photo-gallery"}><ArrowLeft size={15} /> Back to {parent?.name || "Photo gallery"}</Link>}{children.length > 0 && <><div className="gallery-subheading"><p className="section-kicker">Collections</p><h2>{album ? "Inside this album" : "Explore the archive"}</h2></div><div className="album-grid">{children.map((child) => <AlbumCard item={child} key={child.id} />)}</div></>}{album && <div className="gallery-photos"><div className="gallery-subheading"><p className="section-kicker">Photographs</p><h2>{albumPhotos.length ? `${albumPhotos.length} ${albumPhotos.length === 1 ? "photo" : "photos"}` : "No images yet"}</h2></div>{albumPhotos.length ? <div className="photo-grid">{albumPhotos.map((photo, index) => <button className="photo-tile" type="button" key={photo.id} onClick={() => setLightbox(index)} aria-label={`View ${albumName} photo ${index + 1}`}><img src={photo.imageUrl} alt={photo.alt || albumName} /></button>)}</div> : <div className="gallery-empty"><Images size={28} /><p>No images yet under this album.</p></div>}</div>}{!album && !children.length && <div className="gallery-empty"><Images size={28} /><p>No albums yet. Check back soon.</p></div>}</div></section>{lightbox !== null && albumPhotos[lightbox] && <div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label="Photo viewer" onClick={() => setLightbox(null)} onTouchStart={(event) => { touchStart.current = event.touches[0].clientX; }} onTouchEnd={(event) => { if (touchStart.current === null) return; const distance = event.changedTouches[0].clientX - touchStart.current; if (Math.abs(distance) > 45) goPhoto(distance > 0 ? -1 : 1); touchStart.current = null; }}><button className="gallery-lightbox-close" type="button" aria-label="Close photo viewer" onClick={() => setLightbox(null)}><X size={23} /></button>{albumPhotos.length > 1 && <button className="gallery-lightbox-nav prev" type="button" aria-label="Previous photo" onClick={(event) => { event.stopPropagation(); goPhoto(-1); }}><ArrowLeft size={25} /></button>}<img src={albumPhotos[lightbox].imageUrl} alt={albumPhotos[lightbox].alt || albumName} onClick={(event) => event.stopPropagation()} />{albumPhotos.length > 1 && <button className="gallery-lightbox-nav next" type="button" aria-label="Next photo" onClick={(event) => { event.stopPropagation(); goPhoto(1); }}><ArrowRight size={25} /></button>}<span className="gallery-lightbox-count">{lightbox + 1} / {albumPhotos.length}</span></div>}</main>;
}
