import Link from "next/link";
import { ArrowRight, Images } from "lucide-react";
import type { GalleryAlbum, GalleryPhoto } from "@/lib/gallery";

export default function HomepageGallerySection({ albums, photos }: { albums: GalleryAlbum[]; photos: GalleryPhoto[] }) {
  const chosen = albums.filter((album) => !album.parentId).slice(0, 3);
  const coverFor = (album: GalleryAlbum): string => { if (album.coverImageUrl) return album.coverImageUrl; const photo = photos.find((item) => item.albumId === album.id); if (photo) return photo.imageUrl; const child = albums.find((item) => item.parentId === album.id); return child ? coverFor(child) : ""; };
  return <section className="homepage-gallery-section" aria-labelledby="homepage-gallery-title"><div className="container"><div className="homepage-gallery-heading"><div><p className="section-kicker">TLGOM photo gallery</p><h2 id="homepage-gallery-title">Church life in pictures</h2><p>Explore worship services, outreach, and memorable moments from The Life Global Outreach Ministries.</p></div></div>{chosen.length > 0 ? <div className="homepage-gallery-grid">{chosen.map((album) => { const albumPhotos = photos.filter((photo) => photo.albumId === album.id); const children = albums.filter((item) => item.parentId === album.id); const cover = coverFor(album); return <Link className="homepage-gallery-card" href={`/photo-gallery/${album.slug}`} aria-label={`View ${album.name} photo album`} key={album.id}><div className="homepage-gallery-card-image" role="img" aria-label={cover ? `${album.name} album cover` : "No album cover available"} style={{ backgroundImage: cover ? `url("${cover}")` : undefined }}>{!cover && <Images size={24} aria-hidden="true" />}</div><div className="homepage-gallery-card-info"><h3>{album.name}</h3><div><span>{albumPhotos.length} {albumPhotos.length === 1 ? "photo" : "photos"}</span><span>{children.length} nested album{children.length === 1 ? "" : "s"}</span></div></div></Link>; })}<Link className="homepage-gallery-card homepage-gallery-more" href="/photo-gallery" aria-label="View all TLGOM photo gallery albums"><span>TLGOM photo gallery</span><strong>View more albums</strong><ArrowRight size={22} aria-hidden="true" /></Link></div> : <div className="gallery-empty"><Images size={25} aria-hidden="true" /><p>No albums yet. Check back soon.</p></div>}</div></section>;
}
