"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { doc, onSnapshot } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import { defaultContactSettings, type ContactSettings } from "@/lib/contact";

export default function SiteFooter() { const [contact, setContact] = useState<ContactSettings>(defaultContactSettings); useEffect(() => { if (!db) return; return onSnapshot(doc(db, "siteSettings", "contact"), (snapshot) => setContact({ ...defaultContactSettings, ...(snapshot.data() || {}) })); }, []); const hasContact = contact.emails.length > 0 || contact.phones.length > 0; return <footer id="footer" className="public-site-footer">{hasContact && <div className="container public-footer-contact-strip"><strong>Contact TLGOM</strong>{contact.emails.length > 0 && <span>{contact.emails.join(" · ")}</span>}{contact.phones.length > 0 && <span>{contact.phones.join(" · ")}</span>}<Link href="/contact">Send us a message <ArrowRight size={14} /></Link></div>}<div className="container public-footer-worship"><div><h2>Come worship with us</h2><p>Join us at The Life Global Outreach Ministries for worship, prayer, and the Word of God.</p><address>2, Onadairo Street, Abule-Ijoko, Ogun State</address></div><div className="public-footer-map"><iframe title="The Life Global Outreach Ministries location" src="https://www.google.com/maps?q=6.733643%2C3.2849813&z=17&hl=en&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div><div className="container public-footer-grid"><div><h2>The Life Global Outreach Ministries</h2><p>Leading people to Christ massively, worldwide, and establishing them in the Word of God.</p></div><div className="public-footer-links"><strong>Explore</strong><Link href="/about-us">About us</Link><Link href="/contact">Contact us</Link><Link href="/photo-gallery">Photo gallery</Link><Link href="/give">Tithe/Give</Link><Link href="/#prayer-form">Submit a prayer request <ArrowRight size={14} /></Link></div><div className="public-footer-links"><strong>Connect</strong><Link href="/testimony">Share your testimony</Link><Link href="/events">Upcoming events</Link><Link href="/sermons">Video sermons</Link></div></div><div className="container public-footer-bottom"><span>© {new Date().getFullYear()} The Life Global Outreach Ministries</span></div></footer>; }
