"use client";

import { FormEvent, useState } from "react";
import { CheckCircle, LoaderCircle, MessageCircle, Send } from "lucide-react";

type SubmissionType = "prayer" | "testimony";
export type SubmissionContent = { title: string; description: string };
const defaultSubmissionContent: SubmissionContent = { title: "There is room for your story.", description: "Whether you need prayer or want to share what God has done, we are ready to listen." };
function SubmissionForm({ type }: { type: SubmissionType }) {
  const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setBusy(true); setError(""); try { const response = await fetch("/api/submissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type, name: form.get("name"), phone: form.get("phone"), email: form.get("email"), message: form.get("message"), whatsapp: form.get("whatsapp") === "on", consent: form.get("consent") === "on", publicConsent: form.get("publicConsent") === "on" }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not submit."); formElement.reset(); setSent(true); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Could not submit."); } finally { setBusy(false); } }
  const prayer = type === "prayer";
  return <div className="submission-form-card"><div className="submission-form-heading"><span className="submission-form-icon">{prayer ? <MessageCircle size={20} /> : <CheckCircle size={20} />}</span><div><p className="section-kicker">{prayer ? "We are here to stand with you" : "Tell us what God has done"}</p><h3>{prayer ? "Share Your Prayer Request" : "Share Your Testimony"}</h3></div></div>{sent ? <div className="submission-success"><h4>Thank you for sharing.</h4><p>We have received your {prayer ? "prayer request" : "testimony"}.</p><button type="button" className="submission-reset" onClick={() => setSent(false)}>Send another</button></div> : <form onSubmit={submit}><label>Name<input name="name" required autoComplete="name" /></label><label>Phone number<input name="phone" type="tel" required autoComplete="tel" /></label><label className="whatsapp-check"><input name="whatsapp" type="checkbox" /> <span><strong>This number is also on WhatsApp</strong><small>We may use WhatsApp to follow up with care.</small></span></label><label>Email <span className="optional-label">(optional)</span><input name="email" type="email" autoComplete="email" /></label><label className="consent-check"><input name="consent" type="checkbox" /> <span>Send me occasional messages from TLGOM.</span></label><label>{prayer ? "Your prayer request" : "Your testimony"}<textarea name="message" required minLength={10} rows={6} /></label>{!prayer && <label className="consent-check public-consent"><input name="publicConsent" type="checkbox" /> <span><strong>I consent to TLGOM sharing my testimony publicly.</strong><small>We will only share it with your permission.</small></span></label>}{error && <p className="submission-error">{error}</p>}<button className="admin-button submission-submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <Send size={17} />} {busy ? "Sending..." : prayer ? "Submit prayer request" : "Submit testimony"}</button></form>}</div>;
}

export default function SubmissionForms({ content = defaultSubmissionContent }: { content?: SubmissionContent }) { return <section id="prayer-testimony" className="submissions-section"><div className="container"><div className="submissions-intro"><p className="section-kicker">Connect with TLGOM</p><h2>{content.title}</h2><p>{content.description}</p></div><div className="submission-forms-grid"><SubmissionForm type="prayer" /><SubmissionForm type="testimony" /></div></div></section>; }
