import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Facebook, Globe2, Instagram, Linkedin, Youtube } from "lucide-react";
import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import { getPublicCollection } from "@/lib/firebase/public-data";
import { roleInfo, type Leader } from "@/lib/about";

export const dynamic = "force-dynamic";
async function findLeader(slug: string) { const leaders = await getPublicCollection("leadership") as Leader[]; return leaders.find((leader) => leader.slug === slug && leader.published); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const leader = await findLeader(slug); const role = leader ? roleInfo(leader.role).label : "Leadership"; const title = leader ? `${leader.name} | ${role} | TLGOM` : "Leadership profile | TLGOM"; const description = leader?.shortBio || `${role} at The Life Global Outreach Ministries.`; return { title, description, alternates: { canonical: `/about/leadership/${slug}` }, openGraph: { title, description, type: "profile", images: leader?.photoUrl ? [{ url: leader.photoUrl, alt: leader.photoAlt || leader.name }] : undefined } }; }

const socialEntries = (leader: Leader) => [
  ["Website", leader.socialLinks?.website, Globe2], ["Facebook", leader.socialLinks?.facebook, Facebook], ["Instagram", leader.socialLinks?.instagram, Instagram], ["YouTube", leader.socialLinks?.youtube, Youtube], ["LinkedIn", leader.socialLinks?.linkedin, Linkedin],
] as const;

export default async function LeadershipProfilePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const leader = await findLeader(slug); if (!leader) return <main className="about-page"><SiteHeader /><section className="leader-not-found container"><h1>Leadership profile not found</h1><Link href="/about">Return to About TLGOM</Link></section><SiteFooter /></main>; const role = roleInfo(leader.role); const biography = leader.biography || leader.shortBio; const socials = socialEntries(leader).filter((entry) => entry[1]); const personSchema = { "@context": "https://schema.org", "@type": "Person", name: leader.name, jobTitle: role.label, image: leader.photoUrl || undefined, description: leader.shortBio || biography, worksFor: { "@type": "ReligiousOrganization", name: "The Life Global Outreach Ministries" } }; return <main className="leader-profile-page"><SiteHeader /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }} /><article className="leader-profile"><section className="leader-profile-hero"><div className="container"><Link className="leader-profile-back" href="/about"><ArrowLeft size={16} /> About TLGOM</Link><p className="section-kicker">TLGOM leadership</p><h1>{leader.name}</h1><p>{role.label}</p></div></section><section className="container leader-profile-content"><div className="leader-profile-photo">{leader.photoUrl ? <img src={leader.photoUrl} alt={leader.photoAlt || `${leader.name}, ${role.label} at The Life Global Outreach Ministries`} /> : <div aria-hidden="true">TLGOM</div>}</div><div className="leader-profile-copy"><p className="section-kicker">Profile</p><h2>{leader.name}</h2><p className="leader-profile-role">{role.label}</p>{leader.ministry && <p className="leader-profile-ministry">Serving in <strong>{leader.ministry}</strong></p>}<div className="leader-profile-biography">{biography ? biography.split(/\n{2,}/).map((paragraph, index) => <p key={`${leader.id}-${index}`}>{paragraph}</p>) : <p>Profile information will be shared here soon.</p>}</div>{socials.length > 0 && <div className="leader-social-links" aria-label={`${leader.name} links`}>{socials.map(([label, url, Icon]) => <a href={url!} target="_blank" rel="noreferrer" key={label}><Icon size={17} /><span>{label}</span></a>)}</div>}</div></section></article><SiteFooter /></main>; }
