"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { onAuthStateChanged, type User } from "firebase/auth";
import { doc, onSnapshot, setDoc } from "firebase/firestore";
import { ArrowLeft, LoaderCircle, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { auth, db, firebaseReady } from "@/lib/firebase/client";

const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export default function SettingsPage() {
  const router = useRouter(); const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); const [emails, setEmails] = useState(""); const [seo, setSeo] = useState({ title: "The Life Global Outreach Ministries | The word for the world", description: "The Life Global Outreach Ministries exists to lead people to Christ massively, worldwide, and establish them in the Word of God.", image: "" }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, (next) => { setUser(next); setReady(true); }); }, []);
  useEffect(() => { if (ready && !user) router.replace("/control-room?next=/control-room/settings"); }, [ready, user, router]);
  useEffect(() => { if (!db || !user) return; const stopNotifications = onSnapshot(doc(db, "siteSettings", "notifications"), (snapshot) => setEmails(Array.isArray(snapshot.data()?.notificationEmails) ? snapshot.data()?.notificationEmails.join(", ") : "")); const stopSeo = onSnapshot(doc(db, "siteSettings", "seo"), (snapshot) => setSeo((current) => ({ ...current, ...(snapshot.data() || {}) }))); return () => { stopNotifications(); stopSeo(); }; }, [user]);
  async function save(event: FormEvent) { event.preventDefault(); if (!db) return; const list = emails.split(",").map((email) => email.trim()).filter(Boolean); if (list.some((email) => !emailPattern.test(email))) { setError("Enter valid email addresses separated by commas."); setMessage(""); return; } if (!seo.title.trim() || !seo.description.trim()) { setError("SEO title and description are required."); setMessage(""); return; } setBusy(true); setError(""); setMessage(""); try { await Promise.all([setDoc(doc(db, "siteSettings", "notifications"), { notificationEmails: list }, { merge: true }), setDoc(doc(db, "siteSettings", "seo"), { title: seo.title.trim(), description: seo.description.trim(), image: seo.image.trim() }, { merge: true })]); setMessage("Settings saved successfully."); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Could not save settings. Check your connection and try again."); } finally { setBusy(false); } }
  if (!firebaseReady || !ready || !user) return <main className="login-page"><LoaderCircle className="spin" size={28} /></main>;
  return <main className="admin-page"><section className="admin-content"><Link className="admin-back" href="/control-room"><ArrowLeft size={16} /> Back to Control Room</Link><div className="admin-topbar"><div><p className="admin-kicker">Settings</p><h1>Site settings</h1><p className="admin-intro">Control notification recipients and the metadata visitors see when TLGOM is shared.</p></div></div>{message && <div className="admin-notice success">{message}</div>}{error && <div className="admin-notice error">{error}</div>}<form className="sermon-form settings-form" onSubmit={save}><div className="upload-title"><Save size={19} /><div><h2>Submission recipients</h2><p>Separate multiple email addresses with commas.</p></div></div><label>Email addresses<input value={emails} onChange={(event) => setEmails(event.target.value)} placeholder="pastor@example.com, admin@example.com" /><small className="admin-field-help">These addresses receive new prayer requests and testimonies.</small></label><div className="upload-title settings-subheading"><Save size={19} /><div><h2>SEO and social sharing</h2><p>Used for search previews and social links.</p></div></div><label>Site title<input required value={seo.title} onChange={(event) => setSeo({ ...seo, title: event.target.value })} maxLength={70} /></label><label>Site description<textarea required value={seo.description} onChange={(event) => setSeo({ ...seo, description: event.target.value })} maxLength={160} /></label><label>Open Graph image URL <span className="field-note">Optional</span><input type="url" value={seo.image} onChange={(event) => setSeo({ ...seo, image: event.target.value })} placeholder="https://..." /></label><button className="admin-button" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <Save size={17} />} {busy ? "Saving..." : "Save settings"}</button></form></section></main>;
}
